language: c

compiler: gcc

before_script:
    - mkdir build/
    - cd build/
    - cmake ..

script:
    - make -j4

after_script:
    - ./tests/mempool_test

notifications:
    email:
        - jianfan.tw@gmail.com
    on_success: change
    on_failure: always
